//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioExternalService) DeepCopyInto(out *IstioExternalService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioExternalService.
func (in *IstioExternalService) DeepCopy() *IstioExternalService {
	if in == nil {
		return nil
	}
	out := new(IstioExternalService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioExternalService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioExternalServiceEndpoint) DeepCopyInto(out *IstioExternalServiceEndpoint) {
	*out = *in
	out.HealthCheck = in.HealthCheck
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioExternalServiceEndpoint.
func (in *IstioExternalServiceEndpoint) DeepCopy() *IstioExternalServiceEndpoint {
	if in == nil {
		return nil
	}
	out := new(IstioExternalServiceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioExternalServiceEntry) DeepCopyInto(out *IstioExternalServiceEntry) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]IstioExternalServiceEndpoint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioExternalServiceEntry.
func (in *IstioExternalServiceEntry) DeepCopy() *IstioExternalServiceEntry {
	if in == nil {
		return nil
	}
	out := new(IstioExternalServiceEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioExternalServiceHealthCheck) DeepCopyInto(out *IstioExternalServiceHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioExternalServiceHealthCheck.
func (in *IstioExternalServiceHealthCheck) DeepCopy() *IstioExternalServiceHealthCheck {
	if in == nil {
		return nil
	}
	out := new(IstioExternalServiceHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioExternalServiceList) DeepCopyInto(out *IstioExternalServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IstioExternalService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioExternalServiceList.
func (in *IstioExternalServiceList) DeepCopy() *IstioExternalServiceList {
	if in == nil {
		return nil
	}
	out := new(IstioExternalServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioExternalServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioExternalServiceSpec) DeepCopyInto(out *IstioExternalServiceSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]IstioExternalServiceEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioExternalServiceSpec.
func (in *IstioExternalServiceSpec) DeepCopy() *IstioExternalServiceSpec {
	if in == nil {
		return nil
	}
	out := new(IstioExternalServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioExternalServiceStatus) DeepCopyInto(out *IstioExternalServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioExternalServiceStatus.
func (in *IstioExternalServiceStatus) DeepCopy() *IstioExternalServiceStatus {
	if in == nil {
		return nil
	}
	out := new(IstioExternalServiceStatus)
	in.DeepCopyInto(out)
	return out
}
